# version キーは削除（警告回避）
services:
  app:
    build: .
    volumes:
      - .:/app:cached
    ports:
      - "8050:8050"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    # Dockerfile の CMD を使うので command は消すか、使うなら絶対パスで
    # command: /opt/venv/bin/python -m dash_app.app
