RAW_CSV_PATH: data/wait_times.csv
MASTER_CSV_PATH: data/master/pavilion_master.csv
DB_PATH: data/db/wait_times.db
TABLE_NAME: wait_times
PAVILION_DIM_CSV: data/master/pavilion_dim.csv
PAVILION_ALIAS_CSV: data/master/pavilion_alias.csv
GEOJSON_DIR: data/geo
