name: Scrape Wait Times from Google Sheet

on:
  schedule:
    - cron: '0 * * * *'  # 毎時実行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run scraper
        run: python scripts/fetch_data.py

      - name: Commit & push CSV file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add wait_times.csv
          git commit -m "Update wait times data" || echo "No changes to commit"
          git push
